### ISSUE TITLE
Bug: No message when wrong format for Summary command is used

### ISSUE THREAD

**Issue by thisisaditya17** [AY2425S1-CS2103T-T09-2/tp#128]
No usage message is showed when wrong format of summary command is used

<img width="1195" alt="image" src="https://github.com/user-attachments/assets/382026cf-bf7c-4684-bf93-22196700718b">

**Comment by dominic2412** [comment]
Tried to fix this but i think it might be too to identify this input case ..

**Comment by Darren-Tung** [comment]
I will reassign this to v1.6
