### ISSUE TITLE
Bug: Skills field doesn't accept skills with space

### ISSUE THREAD

**Issue by rithanisk** [AY2425S1-CS2103T-T09-2/tp#132]
Unable to add person because "time management" has a space

<img width="1254" alt="image" src="https://github.com/user-attachments/assets/b44124b5-0251-4be6-8aa5-be130fc2a988">

**Comment by Darren-Tung** [comment]
This is a duplicate issue

**Comment by Darren-Tung** [comment]
I will close this since this is fixed
