### ISSUE TITLE
Bug: Overview panel changes from summary details to person details

### ISSUE THREAD

**Issue by rithanisk** [AY2425S1-CS2103T-T09-2/tp#133]
When the overview panel contains the summary details and the user inputs "delete 1", the overview panel gets updated with the new 1st person's details. (This only happens when the first person is deleted and not any other index).
<img width="1204" alt="image" src="https://github.com/user-attachments/assets/e9609856-6380-4ecc-b622-2aa0721d03c4">

**Comment by Darren-Tung** [comment]
I shall also change this to v1.6

**Comment by thisisaditya17** [comment]
Cannot replicate
I am closing it then
