### ISSUE TITLE
Bug: Edit command with index missing message

### ISSUE THREAD

**Issue by rithanisk** [AY2425S1-CS2103T-T09-2/tp#134]
When user inputs "edit <index>" there should be a message that says "please specify at least one field..."

<img width="1200" alt="image" src="https://github.com/user-attachments/assets/2c4502be-ad21-41fa-83ef-bd12c6f9c0c2">

**Comment by Darren-Tung** [comment]
I found that the issue is because of the fixing of the UI windows

**Comment by Darren-Tung** [comment]
This has been fixed
