### ISSUE TITLE
[PE-D][Tester C] Typo in Constraints of fields table → SKILLS

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T09-2/tp#182]
expected:
The team might have made a typo as shown in the provided example in the screenshot, resulting in the skills `Java` and `Python` not being properly separated.

actual:
![image.png](https://raw.githubusercontent.com/celeschai/ped/main/files/3fb163e0-a497-43d9-affd-fdf494f43247.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: celeschai/ped#1

**Comment by Darren-Tung** [comment]
I wrote this and this was on purpose. I wanted to say you can include the comma, but I guess drawing a distinction is better.
