### ISSUE TITLE
[PE-D][Tester A] Index such as 000001, 001 are accepted

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T09-2/tp#196]
When using indexes that are padded with `0`s at the start such as `000001`, this input is accepted by commands which have index parameter (e.g. `add` & `delete`) and is treated as `1`.

For example, executing `delete 00001` deletes the first person in the list.
This behaviour should only be exhibited by running `delete 1`

Such inputs should not be considered as valid indexes.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: LeongWZ/ped#1

**Comment by Darren-Tung** [comment]
This can be said to be a feature.
