### ISSUE TITLE
[PE-D][Tester E] Validity of Phone Numbers

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T09-2/tp#205]
![Screenshot 2024-11-08 at 5.08.12 PM.png](https://raw.githubusercontent.com/waihin26/ped/main/files/d4517f65-f1b1-4733-a5a8-e01e964b43e7.png)

Right now when we add a new candidate into the system, it only supports the use of numbers as valid phone numbers. However i believe that it should accept spaces for convenience, ie "9238 8172" should also be accepted. Additionally, HRs may work with people from foreign backgrounds. Can also consider accepting phone numbers with country codes ie "+1 8271 8127 8172" for international workers. (Considering Singapore's diverse background)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: waihin26/ped#9

**Comment by Darren-Tung** [comment]
I guess this is a small limitation. You may update the UG under the fields section
