### ISSUE TITLE
[PE-D][Tester B] Documentation bug (UG) - constraints of skills field 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T09-2/tp#208]
Expected output: `Java`, `Python`, `C++`
Actual output: `Java, Python`, `C++`

![image.png](https://raw.githubusercontent.com/PeterHW963/ped/main/files/f63f0da6-2201-4365-a93c-813893ddcf07.png)

Reasons for severity: Cosmetic issues that may be slightly misleading and might confuse the users upon reading UG. In particular, whether there should be comma separated values inside the skills input or will the comma be generated on its own upon multiple inputs, or other guesses.

Suggestions: Rectify the UG

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: PeterHW963/ped#5

**Comment by Darren-Tung** [comment]
I was the one who wrote this. I wanted to say that 'Java, Python' is a valid input and this is not a bug. You may change it to how you see fit
