### ISSUE TITLE
[PE-D][Tester D] Command box does not allow scrolling and/or is not wrapped

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T09-2/tp#217]
![image.png](https://raw.githubusercontent.com/hansneddyanto/ped/main/files/756fc971-b3e0-489d-8b90-68a87fa2806d.png)

It's very inconvenient for users to have to look one by one where is the error in such a long string of text, and it takes even longer time without the scrolling function and the box is not wrapped.

It would be very helpful if it can scroll and/or the text is wrapped

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: hansneddyanto/ped#4

**Comment by Darren-Tung** [comment]
## Task
You may code out the wrapper but not the scroll.

## Reference
![image](https://github.com/user-attachments/assets/5d55c75c-2bb7-4215-bd0f-378b1911dadd)
As this behavior does hinder normal usage, we can change this. We also cannot resize the window.

**Comment by thisisaditya17** [comment]
I am not changing it yet, but I feel it is a good to have feature. You can use keyboard to go around.
Its a nice-to-have feature but i dont think it hinders anything.
