### ISSUE TITLE
[PE-D][Tester A] Add and edit commands accept individual skill which is more than 40 characters long

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T09-2/tp#222]
After running `edit 1 s/` or `add n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 dr/Software Engineer s/ ex/Project Manager at Google from 2010-2020 st/Interviewed note/apple t/friends t/owesMoney`, a warning message came up: `Skills should be a non-empty string consisting of alphabetic characters, separated by commas. Each skill should be between 1 and 40 characters long. We do also accept spacing, '#' and ':'`.

This shows that each skill should not be more than 40 characters long.

These command examples with skill field containing a skill with more than 40 characters ran successfully:
- `add n/alicealicealicealicealicealice p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 dr/Software Engineer s/javajavajavajavajavajavajavajavajavajavaj ex/Project Manager at Google from 2010-2020 st/Interviewed note/Super confident t/friends t/owesMoney`
- `edit 1 s/javajavajavajavajavajavajavajavajavajavaj`

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: LeongWZ/ped#8

**Comment by Darren-Tung** [comment]
Change to this "^([A-Za-z0-9#:+]{1}[A-Za-z0-9#:+ ]{0,39})(, [A-Za-z0-9#:+]{1}[A-Za-z0-9#:+ ]{0,39})*$"
