### ISSUE TITLE
[PE-D][Tester D] Filter by job not allowed

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T09-2/tp#239]
Filter should also be done by other things, such as Desired Role. This helpful feature is not available in the app, when it is obviously required by the user. HR deals with a lot of job roles at the same time, and not being able to filter using job roles is a huge missing functionality.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: hansneddyanto/ped#15

**Comment by Darren-Tung** [comment]
## Thoughts
We did not advertise that we will filter by desired role. Hence, this is consider a small issue, but I find that this is a reasonable enhancement to make. 

## Task
1. You should create a section under UG called 'Appendix: Planned Enhancements'.
2. Add this issue in.
