### ISSUE TITLE
[PE-D][Tester A] List panel is removed on the UI when list is empty

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T09-2/tp#243]
The list panel seems to be removed and replaced with a black area when the list is empty.

Non-empty list:
![image.png](https://raw.githubusercontent.com/LeongWZ/ped/main/files/07a06546-c771-47a7-be5c-56e07058b015.png)

Empty list:
![image.png](https://raw.githubusercontent.com/LeongWZ/ped/main/files/fe76d66c-474b-4847-a3ea-3d4d4d2fd066.png)

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: LeongWZ/ped#12

**Comment by Darren-Tung** [comment]
This is considered as a feature so we can't change it. Hence, we need a 'Known Bug' section and write this in

**Comment by thisisaditya17** [comment]
Added this in known enhancement for now,
Will decide later whether to cover it in known issues or not in UG
