### ISSUE TITLE
Create a Command to add a new field (Application Status)

### ISSUE THREAD

**Issue by Darren-Tung** [AY2425S1-CS2103T-T09-2/tp#47]
# Objective
Create a new command to add the application status as a field in the contact list. The field name will be 'Status'.

# Context
From the recruiter's and HR professionals' point of view, there is a need to view the candidates' application status so they can track what to do with the candidate. Hence, it is important to have it as a field in the contact list.

**Comment by dominic2412** [comment]
LGTM
