### ISSUE TITLE
Week 7 - Adding a photo (Dominic) 

### ISSUE THREAD

**Issue by dominic2412** [AY2425S1-CS2103T-T09-2/tp#5]
Everyone has to add their photo

Add a suitable photo of yourself
The filename of the profile photo should be docs/images/github_username_in_lower_case.png
Note the need for lower case (why lowercase?) e.g. JohnDoe123 -> docs/images/johndoe123.png not docs/images/JohnDoe123.png.
If your photo is in jpg format, name the file as .png anyway.

**Comment by Darren-Tung** [comment]
This task is done, hence I will just help close it
